name = "trips-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "trips.prenticew.com/api/*", zone_name = "prenticew.com" }
]

[vars]
CF_ACCESS_TEAM_DOMAIN = "pw10n.cloudflareaccess.com"
CF_ACCESS_AUDIENCE = "3af39f6c701b3903969a5b09993f6994dcbaff170711173d037e2bcb95c325f5"
BOOTSTRAP_ADMIN_EMAIL = "admin@trips.dev"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "trips-db"
database_id = "PROD_DB_ID_PLACEHOLDER"
migrations_dir = "drizzle"
